### ISSUE TITLE
Offline mode is broken in actuators now. 

### ISSUE THREAD

**Issue by tkevinbest** [neurobionics/opensourceleg#266]
## 🐛 Bug Report

Passing the flag `offline=True` to the actuator classes doesn't work anymore. It raises an exception that the joint is not connected... which is kinda the point. 

### Code sample
```
knee = DephyActuator(tag="Knee", gear_ratio=9*83/18, offline=True)
with knee:
    knee.home()
```

### Environment

pi on NB image
```

### Screenshots

![image](https://github.com/user-attachments/assets/e0ef9542-1ec4-466a-9db0-9a573566c43a)

**Comment by tkevinbest** [comment]
Can anyone confirm that this is still a problem?

**Comment by tkevinbest** [comment]
I can confirm that this is still an issue:
```
Traceback (most recent call last):
  File "/home/tkbest/OSLv2-Control/Code/Python/MAIN.py", line 82, in <module>
    with osl, datalog:
  File "/home/tkbest/OSLv2-Control/.venv/lib/python3.11/site-packages/opensourceleg/robots/base.py", line 68, in __enter__
    self.start()
  File "/home/tkbest/OSLv2-Control/.venv/lib/python3.11/site-packages/opensourceleg/robots/osl.py", line 24, in start
    super().start()
  File "/home/tkbest/OSLv2-Control/.venv/lib/python3.11/site-packages/opensourceleg/robots/base.py", line 101, in start
    actuator.start()
  File "/home/tkbest/OSLv2-Control/.venv/lib/python3.11/site-packages/opensourceleg/actuators/decorators.py", line 40, in wrapper
    raise ActuatorConnectionException(tag=self.tag)
opensourceleg.logging.exceptions.ActuatorConnectionException: knee is not connected
```
